`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: ayengec
// Engineer: ayengec
// 
// Create Date: 29.05.2021 18:58:55
// Design Name: uart_receiver
// Module Name: uart_receiver
// Project Name: UART RECEIVER DESIGN WITH SYSTEMVERILOG
// Target Devices: Artix-7
// Tool Versions: 2020.1
// Description: This module explains how uart receiver is designed.
// 
// Dependencies: This module needs to baudrate generator for implemented design or some clock 
// sources with minimum double clock according to transmitter clock
// 
// Revision:-
// Revision 0.01 - File Created
// Additional Comments:-
// 
//////////////////////////////////////////////////////////////////////////////////

module uart_receiver#(parameter DATA_WIDTH_NUMBER=8, STOP_BITS_NUMBER=2)(
    input  logic data_in,           // serial data input
    input  logic sample_clk,        // sample clock is equal to half baud_clock
    input  logic rst_n,             // system reset

    output logic [DATA_WIDTH_NUMBER-1:0] data_out,  // how many data bit on a frame sending by transmitter
    output logic rx_done,           // only '1' when receiving process successfully
    output logic rx_error           // if stop bits are not high'1' as pre-defined number, this error is going to high '1'
    );

    // States of Receiving process
    typedef enum logic [1:0] {
        IDLE,
        DATA,
        STOP
    } state_t;

    state_t state, next_state;                  // state object is instantiated from state_type
    
    shortint unsigned idx;              // index of data or stop bits
    shortint unsigned clk_counter;      // we use half clock. To sync after start bit's middle

    // Control signals generated by FSM for Datapath
    logic count_en, rst_cnt_en, rst_idx_en, shift_data_en, inc_idx_en, set_done_en, set_err_en;

    // ==========================================
    // 1. CONTROL PATH (Next State & Control Logic)
    // ==========================================
    always_ff @(posedge sample_clk or negedge rst_n) begin
        if (!rst_n) state <= IDLE;
        else        state <= next_state;
    end

    always_comb begin
        next_state    = state;      // Default assignments
        count_en      = 1'b0;
        rst_cnt_en    = 1'b0;
        rst_idx_en    = 1'b0;
        shift_data_en = 1'b0;
        inc_idx_en    = 1'b0;
        set_done_en   = 1'b0;
        set_err_en    = 1'b0;

        case (state)
            IDLE: begin
                // if serial data_in is coming LOW, it means that start bit is coming
                if (data_in == 1'b0) begin         
                    if (clk_counter < 1) begin  
                        count_en = 1'b1;
                    end else begin
                        next_state = DATA;  // after being sure start bit has come, go to DATA state
                        rst_cnt_en = 1'b1;
                        rst_idx_en = 1'b1;
                    end
                end else begin
                    rst_cnt_en = 1'b1;
                end                     
            end

            DATA: begin
                if (idx == DATA_WIDTH_NUMBER) begin      // if all data bits are completed, check stop bits
                    next_state = STOP;
                    rst_cnt_en = 1'b1;
                    rst_idx_en = 1'b1; 
                end else begin
                    if (clk_counter < 1) begin
                        count_en = 1'b1;
                    end else begin
                        shift_data_en = 1'b1;
                        inc_idx_en    = 1'b1;
                        rst_cnt_en    = 1'b1;
                    end
                end
            end

            STOP: begin
                if (idx == STOP_BITS_NUMBER) begin      // check stop bits are valid or invalid
                    next_state  = IDLE;
                    set_done_en = 1'b1;
                    rst_idx_en  = 1'b1;
                end else begin
                    if (clk_counter < 1) begin
                        count_en = 1'b1;
                    end else begin
                        if (data_in) begin
                            inc_idx_en = 1'b1;          // stop bit is valid (HIGH), increment index
                        end else begin
                            set_err_en = 1'b1;          // if data_in isn't HIGH, there is an error
                            next_state = IDLE;
                        end
                        rst_cnt_en = 1'b1;
                    end
                end
            end
        endcase
    end

    // ==========================================
    // 2. DATAPATH (Data Routing and Counters)
    // ==========================================
    always_ff @(posedge sample_clk or negedge rst_n) begin
        if (!rst_n) begin       // if system reset is low, all outputs are going to Z
            data_out    <= 'hZ;
            rx_done     <= 1'bZ;
            rx_error    <= 1'bZ;
            idx         <= 0;
            clk_counter <= 0;
        end else begin
            // Default resets for IDLE state logic
            if (state == IDLE) begin
                rx_done <= 1'b0;
            end
            
            // Output flags logic
            if (set_done_en) rx_done <= 1'b1;
            if (set_err_en)  rx_error <= 1'b1;

            // Clock counter logic
            if (rst_cnt_en) begin
                clk_counter <= 0;
            end else if (count_en) begin
                clk_counter <= clk_counter + 1;
            end

            // Index and Data logic
            if (rst_idx_en) begin
                idx <= 0;
            end else begin
                if (inc_idx_en) idx <= idx + 1;
                if (shift_data_en) data_out[idx] <= data_in;
            end
        end
    end
endmodule
